/*A coloured triangle is created from a row of colours, each of which is red, green or blue. 
Successive rows, each containing one fewer colour than the last, are generated by considering the two touching colours in the previous row. 
If these colours are identical, the same colour is used in the new row. If they are different, the missing colour is used in the new row. 
This is continued until the final row, with only a single colour, is generated.
*/
function triangle(row) {
  if (row.length === 1) return row; // base case
  
  let next = [] // variable to store next row
//   brute force conditionals
  for (let i = 0; i < row.length - 1; i++){
      if (row[i]  === row[i+1]){
        next.push(row[i]);
    } else if (row[i] === 'G'){
      if (row[i+1] === 'R') next.push('B');
      if (row[i+1] === 'B') next.push('R');
    } else if (row[i] === 'R'){
      if (row[i+1] === 'G') next.push('B');
      if (row[i+1] === 'B') next.push('G');
    } else {
      if (row[i+1] === 'G') next.push('R');
      if (row[i+1] === 'R') next.push('G');
    }
  }
  // recurrence
  return triangle(next.join(''));
}